### ISSUE TITLE
Why does the normalizer remove the `Compacted` flag?

### ISSUE THREAD

**Issue by ctrlcctrlv** [alerque/sfdnormalize#5]
I don't think it should, but it does.

![image](https://user-images.githubusercontent.com/838783/113480866-94dbb800-9464-11eb-8b27-828e325585b3.png)

**Comment by alerque** [comment]
I don't know. I can confirm that the latest Perl version of this script I was able to trace (f5657dc) does not have this particular cleanup, and the first Python version (f5657dc) does. That being said I know there is more history to the Python version than what made it into this repo, but it was scattered around embedded in various font repositories. As such `git blame` isn't much use here.

If there is a decent justification for removing it (i.e. leaving it well enough alone) I'd be happy to accept a PR.

**Comment by alerque** [comment]
Isn't this flag more about the state of the GUI than about the font itself? I seem to recall that FF has a UI setting that the user can enable this by default or not, this appears to be an attempt to keep that UI preference from making it's way into the font data.

What's the logic for not removing it?

**Comment by ctrlcctrlv** [comment]
Compacting the encoding isn't simply a UI thing in my view. If you add slots to a compacted encoding, FontForge will set the encoding as `Custom` (this is the easiest way to make a `Custom` encoding). If you add slots to an uncompacted encoding, it will remain in `UnicodeBMP` (or whatever encoding is set).

So, my scripts won't work the same if it expects that the first (Python API) `font.createChar` call will make a `Custom` encoding but the normalizer made the font not compacted.

Maybe there should be some kind of way to add options if some folks are considering this UI-only and others aren't. Personally when I compact a font I'm never going to uncompact it.

**Comment by alerque** [comment]
That sounds like a FontForge nonsense that should be fixed in FF. I understand your use case where you don't want the option to go away, but correcting it would nullify the opposite use case: where you don't want it to leak in. Right now under File→Preferences→Open Font there is a setting called "CompactOnOpen". This causes FF to change this setting on any font sources you touch. As such FF has implemented it is a **user preference** not a project/font preference that leaks in to every file you touch whether the project calls for it or not. Hence normalizing it away so that different people can keep using the same repos while keeping their own UP preferences seems correct to me.

I'm happy to extend a way to configure what things happen or not, but given your scenario it sounds to me like you should be more explicit in your script with the FF API and instead of expecting the encoding to be changed magically, set it to what it should be explicitly. Using a UI preference as a a shortcut to get a certain encoding seems like it shouldn't have happened in the first place.

**Comment by ctrlcctrlv** [comment]
I'm working on my own font editor for a reason :-)

OK, if you don't want this merged, I'll just write a quick script to run after the normalizer to restore the flag for me.

**Comment by khaledhosny** [comment]
FontForge would often crash on me or do some other crazy stuff when building fonts with compact encoding, that is why it was normalized away.

**Comment by ctrlcctrlv** [comment]
I see. A lot of compacting bugs have been fixed since you were regularly using FontForge. I filed some reports which led to patched bugs by Skef and Jeremy upon collaboration (see e.g. fontforge/fontforge#4124, fontforge/fontforge#4284), I also patched at least one of these compacting bugs myself. (See e.g. fontforge/fontforge#3939)

I believe compacting to be stable in non-CID fonts now. At least, I regularly compact/uncompact/re-encode my fonts, and no longer get crashes. However, we know that CID fonts and compacting are, to put it mildly, extremely buggy. Actually, the project's current advice is that everyone immediately compact CID fonts upon import if they only have it in CID font format. ([#D6](https://github.com/fontforge/fontforge/wiki/Community-guidelines#D6))

So, I'd say, that if that's the motivation for adding it, then it's no longer a good motivation. However, the `-k Compacted` flag I added works fine for me, so changing the default isn't a priority for me either.
