### ISSUE TITLE
Ramifications of updating SplineFontDB

### ISSUE THREAD

**Issue by alerque** [alerque/sfdnormalize#7]
The changes in #6 update the SplineFontDB from 3.0 to 3.2 by default. Are there any possible side effects to this for downstream projects? It doesn't seem to phase mine at all, but I'm not very familiar with how FontForge handles updates or what other programs may read this value. I realize they can adjust this default, but if it will break anything for anybody I'd rather introduce it behind a non-default flag first, then later bump the default.

If no possible problems are foreseen I think we can move ahead with a new release tag, the logic for that makes sense to me.

**Comment by ctrlcctrlv** [comment]
There's nothing for you to worry about @alerque. We did a few version bumps because we added some new items having to do with background images. I confirmed that these new items are understood fine by `sfdnormalize`. The version bump is so users of old FontForge versions know that files with these new items can't be understood by their version.

It is perfectly OK to consider any 3.0 SFD as being a 3.2 SFD. Just, not every 3.2 SFD can be a 3.0 SFD. So, because `sfdnormalize` understands the new items without issue, it's actually downgrading files with them in a way old FontForge's won't understand. The new default version reflects its actual state of SFD conformity.

**Comment by alerque** [comment]
Got it. I think the only catch would be if used with files produced by an old FontForge (i.e. with none of the new keys) was normalized it would appear to be no longer compatible with the same version of FF that created it, but given the distro penetration the latest release has I think I'll let that be somebody else's problem.

**Comment by khaledhosny** [comment]
I was downgrading because I didn't use any of the new features and the version of FontForge available on Travis would choke on the newer SFD version.

**Comment by alerque** [comment]
Thanks for the background. It's not adjustable from the CLI, and defaults to 3.2. Travis isn't an issue for me given their lack of support for FOSS projects, they have newer images and *could* be setup with a fresher FontForge, and if that's not acceptable to some project they can add CLI args to normalize to an older version.
